const $=id=>document.getElementById(id);const fmt=(x,n=2)=>Number.isFinite(x)?x.toLocaleString('en-US',{minimumFractionDigits:n,maximumFractionDigits:n}):'—';let current={...DEFAULTS},last=null;const labels={};
function field(id,label,unit='',hint='',options=null){labels[id]=label;const val=current[id];const input=options?`<select id="${id}">${options.map(([v,t])=>`<option value="${v}" ${String(val)===String(v)?'selected':''}>${t}</option>`).join('')}</select>`:`<input id="${id}" type="number" step="any" value="${val}" aria-label="${label}">`;return `<div class="field"><label for="${id}">${label}</label><div class="control">${input}${unit?`<span class="unit">${unit}</span>`:''}</div>${hint?`<small>${hint}</small>`:''}</div>`;}
function check(id,text){labels[id]=text;return `<label class="checklabel"><input type="checkbox" id="${id}" ${current[id]?'checked':''}>${text}</label>`;}
function card(title,fields,note=''){const advanced=['材料與立柱','陣風反應','托架斷面'].includes(title);return `<details class="card input-card" ${advanced?'':'open'}><summary><span>${title}</span><span class="fold-hint">${advanced?'進階參數':'參數設定'}</span></summary><div class="fields">${fields}</div>${note?`<p class="hint">${note}</p>`:''}</details>`;}
function build(){
 $('geometry').innerHTML=card('搭設尺寸',field('top','鷹架頂端離地高程','m')+field('base','鷹架起始離地高程','m')+field('step','每層架高','m','原標準模組 1.725 m')+field('bay','沿牆立框間距','cm')+field('width','內外立柱間寬度','cm')+field('offset','內柱離牆距離 a','cm'),'垂直載重以單一立框的兩支立柱均分；高程用於風速壓，搭設高度為頂端減起始。')+card('材料與立柱',field('d','立柱外徑 D','mm')+field('t','名義壁厚 t','mm')+field('loss','厚度扣減','mm','原碼扣減 0.3 mm')+field('fy','立柱降伏強度 Fy','kgf/cm²')+field('E','彈性模數 E','kgf/cm²')+field('k','有效長度係數 K','')+field('unbraced','無側撐層高倍率','倍')+field('reduction','舊料容許應力折減率','','0 < η ≤ 1；不重複扣減厚度'))+card('重量與工作載重',field('weightMode','每組架重方式','','',[['auto','依原程式估算'],['manual','輸入實測重量']])+field('weight','實測每層每立框組重','kgf')+field('dd','交叉拉桿外徑','mm')+field('dt','交叉拉桿壁厚','mm')+field('deck','踏板總寬','cm')+field('work','同時作業層數','層')+field('dl','每作業層附加靜載','kgf/立框')+field('ll','每作業層活載','kgf/立框'),'DL / LL 為每立框分攤的總荷重，不是 kgf/m²；踏板自重已在每層架重，不應重複加入。');
 $('wind').innerHTML=card('基地風場',field('v','基本設計風速 V₁₀(C)','m/s','50 年回歸期、地況 C、10 m 高、10 分鐘平均風速')+field('terrain','地況','','',[['A','A｜密集高樓市中心'],['B','B｜市郊、城鎮'],['C','C｜平坦開闊、海岸']])+field('importance','用途係數 I','','不因臨時工期自動折減',[['1','1.0｜一般預設'],['1.1','1.1｜提高用途係數'],['0.9','0.9｜須確認用途適用']])+field('kzt','地形係數 Kzt','','平地 1.0；山丘、山脊、懸崖依 §2.6 求得'),'臺北市參考值 42.5 m/s；其他基地請依 §2.4 與表 2.21 核定。A / B 需滿足上風向延伸範圍，不能僅依地址選擇。')+card('陣風反應',field('gmode','G / Gf 計算方式','','',[['fixed','普通結構簡化 G = 1.88'],['rigid','普通結構詳細計算'],['flexible','柔性結構詳細 Gf'],['manual','輸入專案分析 G / Gf']])+field('fn','基本自然頻率 fn','Hz','fn < 1 Hz 應考慮柔性反應')+field('beta','結構阻尼比 β','','0.01 = 1%；需與實際結構相符')+field('gm','專案 G / Gf','','僅專案輸入模式使用')+field('windL','受風系統順風深度 L','m','Gf 的動力分析尺寸'),'動力參數應對應實際受風與支承系統，不能直接拿建築物週期當施工架週期。')+card('受風面積與係數',field('windB','受風系統沿牆總寬 B','m','用於陣風與實體面板長寬比；非壁連桿間距')+field('cover','遮網實體率 s','','0 = 無網，1 = 完全實體')+field('phiMode','總實體率 φ','','',[['auto','由原鋼材投影＋遮網估算'],['manual','輸入實測總實體率']])+field('phi','實測總實體率 φ','','含鋼材與網布重疊後的實體面積比')+field('windMode','風力模型','','',[['auto','表 2.10 / 2.11 工程類比'],['manual','自訂 Cf × 實體面積'],['net','專案淨風壓 Cnet × 全面積']])+field('cf','自訂風力係數 Cf','','須與選用的實體投影面積一致')+field('netC','專案淨風壓係數 Cnet','','已含陣風：p = q × Cnet，不再乘 G'),'以頂端風速壓計算全額壁連桿分攤面積，作為高度包絡。實體率不等於氣動折減率；附著式鷹架須確認建築物干擾、角隅、局部壓力與反向風。')+card('壁連桿配置',field('tieX','水平分攤間距 Sx','m')+field('tieY','垂直分攤間距 Sy','m')+field('tieT','整組容許拉力','kgf','含桿件、接頭、錨定系統')+field('tieC','整組容許壓力','kgf','需考慮壓桿挫屈；不得直接沿用拉力'),'預設 883 kgf 取自原碼壁連桿拉力示例；壓力數值只是示範，必須另行確認。')+`<div class="notice">${check('windConfirmed','已確認現地風場、風力模型與施工架適用條件')}<p>勾選只記錄工程假設已覆核，不改變檢核數值。</p></div>`;
 $('bracket').innerHTML=`<article class="card"><h2 class="toggle-title"><input type="checkbox" id="bracketEnabled" ${current.bracket?'checked':''}><label for="bracketEnabled">計算三角托架與錨栓</label></h2><p class="hint">關閉後僅檢核立柱與壁連桿，不代表落地基礎已通過檢核。</p></article>`+`<div id="bracketFields">`+card('托架幾何與分攤',field('B','托架水平長 B','cm')+field('D','托架垂直深 D','cm')+field('spacing','托架沿牆間距','cm')+field('pieces','每處並列托架片數','片','等分載重；不視為組合斷面')+field('bracketFy','托架降伏強度 Fy','kgf/cm²')+field('bracketK','斜桿有效長度係數 K',''),'AC 水平桿、BC 斜桿；兩支柱作用位置 a 與 b = a + 內外柱寬。')+card('托架斷面',field('section','角鋼規格','','原程式 23 種斷面資料',SECTIONS.map((s,i)=>[i,s.name]).concat([['custom','自訂斷面（單軸彎曲）']]))+field('customA','自訂面積 A','cm²')+field('customI','自訂慣性矩 Ix','cm⁴')+field('customS','自訂斷面模數 Sx','cm³')+field('customAw','自訂剪力面積 Aw','cm²')+field('customR','自訂最小迴轉半徑 rmin','cm'),'角鋼彎矩分解至主軸 u/v 檢核；自訂斷面須自行提供最小迴轉半徑，避免忽略弱軸挫屈。')+card('各端錨栓群',field('anchorT','單支基準抗拉容量','kgf','示範：舊表 M16 化錨 2465')+field('anchorV','單支基準抗剪容量','kgf','示範：舊表 M16 化錨 3460')+field('anchorSF','基準容量除數 SF','','若已輸入容許容量，設為 1')+field('anchorN','每片托架每端錨栓數','支','上下各一組；不乘並列片數'),'容量必須符合實際產品、埋深、間距、邊距、混凝土強度及開裂狀態。此處先列個別拉／剪檢核；拉剪互制及混凝土破壞另行設計。')+`</div><div class="notice">${check('capacityConfirmed','已確認壁連桿與錨栓輸入容量的產品及基材依據')}</div>`;
 for(const [key,value]of Object.entries(current)){const el=$(key);if(el){el.addEventListener('input',()=>{current[key]=el.type==='checkbox'?el.checked:key==='section'?el.value:typeof DEFAULTS[key]==='number'?Number(el.value):el.value;if(el.type==='number'&&el.value==='')current[key]=NaN;render();});}}
 $('bracketEnabled').onchange=e=>{current.bracket=e.target.checked;render();};render();}
function traceSection(title,content,open=false){return `<details ${open?'open':''}><summary>${title}</summary>${content}</details>`;}
function render(){const p=current;['weight'].forEach(k=>$(k).disabled=p.weightMode!=='manual');['dd','dt','deck'].forEach(k=>$(k).disabled=p.weightMode==='manual');$('phi').disabled=p.phiMode!=='manual';$('cf').disabled=p.windMode!=='manual';$('netC').disabled=p.windMode!=='net';$('gm').disabled=p.gmode!=='manual';$('beta').disabled=p.gmode!=='flexible';for(const k of ['customA','customI','customS','customAw','customR'])$(k).disabled=p.section!=='custom';$('bracketFields').hidden=!p.bracket;
 document.querySelectorAll('.field input,.field select').forEach(el=>{el.closest('.field').classList.toggle('inactive-field',el.disabled);el.setAttribute('aria-invalid',el.type==='number'&&el.value===''?'true':'false');});const openTrace=Array.from($('trace').querySelectorAll('details')).map(d=>d.open);const r=calculate(p,SECTIONS);last=r;$('errors').hidden=!r.errors.length;if(r.errors.length){$('errors').textContent=r.errors.map(x=>Object.entries(labels).reduce((s,[k,v])=>s.replace(new RegExp('^'+k+' '),v+' '),x)).join('；');$('global').className='global bad';$('global').innerHTML='<strong>輸入需修正</strong>數值修正前不顯示檢核結果';for(const k of ['metrics','checks','diagram','chart','trace','warnings'])$(k).innerHTML='';return;}
 const fail=r.rows.filter(x=>x.ratio>1).length;$('global').className='global'+(fail?' bad':'');$('global').innerHTML=`<strong>${fail?fail+' 項檢核超限':'已計算項目未超限'}</strong>${!p.windConfirmed||!p.capacityConfirmed?'示範參數 · 尚有工程條件待確認':'尚需整體穩定與連接系統審查'}`;
 $('metrics').innerHTML=[['每立框總載重',r.WT,'kgf · '+r.N+' 層'],['單支壁連桿風力',r.w.F,'kgf · 頂端包絡'],['最大使用比',r.worst.ratio,'控制：'+r.worst.name]].map(([a,b,c],i)=>`<div class="metric"><small>${a}</small><b>${fmt(b,i===2?2:0)}</b><em>${c}</em></div>`).join('');
 $('checks').innerHTML=r.rows.map(x=>`<div class="check-row" title="${x.note}"><div class="check-head"><span>${x.name}</span><span><b>${fmt(x.ratio,3)}</b><span class="tag ${x.ratio>1?'ng':''}">${x.ratio>1?'NG':'OK'}</span></span></div><div class="track"><span style="width:${Math.min(x.ratio*50,100)}%;background:${x.ratio>1?'var(--red)':'var(--green)'}"></span></div><small>${fmt(x.demand)} / ${fmt(x.capacity)} ${x.unit}</small></div>`).join('');
 $('warnings').innerHTML='<b>適用條件與待確認事項</b>'+r.warnings.map(x=>`<p>• ${x}</p>`).join('')+'<p>本表僅含所列構件檢核；整體穩定、基礎、風致彎矩與錨栓完整破壞模式尚未驗算。</p>';
 diagram(p,r);chart(p,r);trace(p,r);if(openTrace.length)Array.from($('trace').querySelectorAll('details')).forEach((d,i)=>d.open=openTrace[i]??false);}
function diagram(p,r){const levels=Math.min(r.N,7),x0=115,x1=250,y0=32,y1=232;let grid='';for(let i=0;i<=levels;i++){let y=y1-(y1-y0)*i/levels;grid+=`<path d="M${x0},${y}H${x1}" stroke="#6c91b5" stroke-width="2"/>`;if(i<levels){let y2=y1-(y1-y0)*(i+1)/levels;grid+=`<path d="M${x0},${y}L${x1},${y2}M${x1},${y}L${x0},${y2}" stroke="#acbfd0"/>`;}}
 const s=r.bracket;$('diagram').innerHTML=`<svg viewBox="0 0 570 285" role="img" aria-label="施工架立面與托架受力示意"><defs><marker id="arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0L7,3.5L0,7" fill="#185bce"/></marker></defs><path d="M70 30V240M62 30H78M62 240H78" stroke="#879fb2"/><text x="50" y="146" transform="rotate(-90 50 146)" fill="#617487" font-size="12" text-anchor="middle">搭設 ${fmt(p.top-p.base,2)} m / ${r.N} 層</text><rect x="115" y="32" width="135" height="200" fill="#e9f1fc" opacity="${.2+p.cover*.6}"/>${grid}<path d="M115 32V240M250 32V240" stroke="#234f74" stroke-width="4"/><path d="M97 245H135M230 245H268" stroke="#234f74" stroke-width="3"/><path d="M280 90H258M280 138H258M280 186H258" stroke="#185bce" stroke-width="2" marker-end="url(#arrow)"/><text x="166" y="269" text-anchor="middle" fill="#617487" font-size="12">立框間距 ${fmt(p.bay,0)} cm</text><text x="115" y="20" fill="#617487" font-size="12">立面 / 省略中間層</text>${s?`<path d="M355 70V241" stroke="#c6d3df" stroke-width="9"/><path d="M361 108H530L361 226" fill="none" stroke="#234f74" stroke-width="3"/><circle cx="361" cy="108" r="4" fill="#185bce"/><circle cx="361" cy="226" r="4" fill="#185bce"/><text x="340" y="100" fill="#617487" font-size="12">A</text><text x="340" y="242" fill="#617487" font-size="12">B</text><text x="536" y="114" fill="#617487" font-size="12">C</text><path d="M${361+169*s.a/s.B} 70V103M${361+169*s.b/s.B} 70V103" stroke="#185bce" stroke-width="2" marker-end="url(#arrow)"/><text x="440" y="55" text-anchor="middle" fill="#185bce" font-size="12">每點 P = ${fmt(s.Px,0)} kgf</text><text x="437" y="132" text-anchor="middle" fill="#617487" font-size="12">B = ${fmt(p.B,0)} cm</text><text x="409" y="205" fill="#617487" font-size="12">D = ${fmt(p.D,0)} cm</text><text x="445" y="269" text-anchor="middle" fill="#617487" font-size="12">托架 / 每片受力</text>`:`<text x="350" y="127" fill="#617487" font-size="14">托架計算已關閉</text><text x="350" y="152" fill="#617487" font-size="12">基底承載需另外檢核</text>`}</svg>`;}
function chart(p,r){const max=r.w.F*1.1,pts=r.profile.map(v=>`${55+v.F/max*440},${215-(v.z-p.base)/(p.top-p.base)*175}`).join(' ');let ticks='';for(let i=0;i<=4;i++){let y=215-i*175/4;ticks+=`<path d="M55 ${y}H520" stroke="#e6edf3"/><text x="43" y="${y+4}" text-anchor="end" fill="#617487" font-size="12">${fmt(p.base+(p.top-p.base)*i/4,1)}</text>`;}$('chart').innerHTML=`<svg viewBox="0 0 560 264" role="img" aria-label="高度與壁連桿風力圖，頂端風力 ${fmt(r.w.F)} kgf"><text x="20" y="20" fill="#617487" font-size="12">離地高程 m</text>${ticks}<polyline points="${pts}" fill="none" stroke="#185bce" stroke-width="3"/><circle cx="${55+r.w.F/max*440}" cy="40" r="4" fill="#185bce"/><text x="${55+r.w.F/max*440-10}" y="28" text-anchor="end" fill="#185bce" font-size="13">${fmt(r.w.F,0)} kgf</text>${[0,1,2,3,4].map(i=>`<text x="${55+i*110}" y="238" text-anchor="middle" fill="#617487" font-size="12">${fmt(max*i/4,0)}</text>`).join('')}<text x="520" y="258" text-anchor="end" fill="#617487" font-size="12">風力 kgf / 相同分攤面積 ${fmt(r.w.area)} m²</text></svg>`;}
function trace(p,r){const w=r.w,g=r.g,b=r.bracket;let html=traceSection('01　自重、工作載重與立柱',`<div class="formula">N = ceil[(${p.top} − ${p.base}) / ${p.step}] = ${r.N}<br>每層組重 W₀ = ${fmt(r.W0)} kgf；原估算：立框 ${fmt(r.frame)} + 踏板 ${fmt(r.deckW)} + 拉桿 ${fmt(r.brace)} = ${fmt(r.rawW)} kgf（取整）<br>Wᴅ = N W₀ = ${fmt(r.WD)} kgf<br>W作業 = ${p.work} × (${p.dl} + ${p.ll}) = ${fmt(r.WL)} kgf<br>Wᴛ = ${fmt(r.WT)} kgf；P = Wᴛ / 2 = ${fmt(r.P)} kgf<br>t有效 = ${(p.t-p.loss).toFixed(3)} mm<br>A = π[D² − (D−2t有效)²]/4 = ${fmt(r.sec.A,4)} cm²<br>I = π[D⁴ − (D−2t有效)⁴]/64 = ${fmt(r.sec.I,4)} cm⁴<br>Z = 2I/D = ${fmt(r.sec.Z,4)} cm³；r = √(I/A) = ${fmt(r.sec.r,4)} cm<br>λ = K L/r = ${fmt(r.lambda)}；Cᴄ = √(2π²E/Fy) = ${fmt(r.Cc)}<br>x = λ/Cᴄ；λ < Cᴄ：Fa = (1−x²/2)Fy / (5/3+3x/8−x³/8)<br>λ ≥ Cᴄ：Fa = 12π²E/(23λ²)<br>Fa = ${fmt(r.Fa)}；η Fa = ${fmt(r.allow)} kgf/cm²<br>fa = P/A = ${fmt(r.fa)} kgf/cm²</div><p>單位重採原碼 0.78 kgf/(cm²·m)，斜撐長度固定 1.829 m；名義斷面計重量，有效斷面計承載。</p>`,true);
 html+=traceSection('02　現行耐風公式與壁連桿',`<p>${w.method}。採頂端 z = ${p.top} m 對各分攤面積包絡，不套用建築物 Cp / Cpi 直接相加。</p><div class="formula">K(z) = 2.774[max(z,5)/zg]^(2α) = ${fmt(w.Kz,4)}<br>q(z) = 0.06 K(z) Kzt [I V₁₀(C)]² = ${fmt(w.q)} kgf/m²<br>G / Gf = ${fmt(g.G,4)}<br>鋼材投影率 = ${fmt(w.steel,4)}；φ = ${p.phiMode==='manual'?'手動實測':'s + (1−s) × 鋼材投影率'} = ${fmt(w.phi,4)}<br>${p.windMode==='net'?'Cnet':'Cf'} = ${fmt(w.cf,4)}；面積倍率 = ${fmt(w.areaFactor,4)}<br>p = ${p.windMode==='net'?'q Cnet':'q G Cf × 面積倍率'} = ${fmt(w.pressure)} kgf/m²<br>A分攤 = Sx Sy = ${p.tieX} × ${p.tieY} = ${fmt(w.area)} m²<br>F = p A分攤 = ${fmt(w.F)} kgf = ${fmt(w.F*.00980665)} kN<br>相同面積之舊普通分支參考 F舊 = ${fmt(w.oldF)} kgf（G = 1.77，Kzt = 1）</div><p>原式比較僅供查核，不是可選設計荷重；若使用柔性、專案風壓或實測 φ，兩者模型不同，不能只比較百分比判定安全。</p>`);
 html+=traceSection('03　陣風反應中間值',`<div class="formula">z̄ = max(0.6h,zmin) = ${fmt(g.zbar)} m<br>Lz̄ = ℓ(z̄/10)^ε = ${fmt(g.Lz)} m<br>Iz̄ = c(10/z̄)^(1/6) = ${fmt(g.Iz,4)}<br>Q = [1+0.63((B+h)/Lz̄)^0.63]^−½ = ${fmt(g.Q,4)}<br>普通詳細：G = 1.927(1+1.7×3.4×Iz̄×Q)/(1+1.7×3.4×Iz̄)<br>柔性：Gf = 1.927[1+1.7 Iz̄ √(3.4²Q²+gR²R²)]/(1+1.7×3.4×Iz̄)${p.gmode==='flexible'?`<br>Vz̄ = ${fmt(g.V)} m/s；N₁ = ${fmt(g.N,4)}；Rn = ${fmt(g.Rn,4)}<br>Rh = ${fmt(g.Rh,4)}；RB = ${fmt(g.Rb,4)}；RL = ${fmt(g.Rl,4)}<br>R = ${fmt(g.R,4)}；gR = ${fmt(g.gr,4)}`:''}<br>本次 G / Gf = ${fmt(g.G,4)}</div><p>普通簡化使用 1.88；柔性詳細依 §2.7 式 (2.13)–(2.19)。β 由使用者設定，未固定套用原碼 2%。</p>`);
 if(b){html+=traceSection('04　三角托架最小功法與應力',`<div class="formula">KGB = 托架間距 / 立框間距 / 片數 = ${fmt(b.KGB,4)}<br>P每點 = (Wᴛ/2) KGB = ${fmt(b.Px)} kgf<br>a = ${b.a}；b = ${b.b}；L = √(B²+D²) = ${fmt(b.L)} cm<br>c = B/L；s = D/L<br>HB = P(a+b)/D = ${fmt(b.HB)} kgf（HA 反向等量）<br>VB = [HB L³sc/3 + HB DB²/2 − P(a³+b³)/6] / [L³c²/3+B³/3] = ${fmt(b.VB)} kgf<br>VA = 2P − VB = ${fmt(b.VA)} kgf<br>Nbc = HB c + VB s = ${fmt(b.NC)} kgf<br>Mbc = |VB B − HB D| = ${fmt(b.MC)} kgf·cm<br>Mac = max(|VA a|, |VA B−P(B−a)−P(B−b)|, |VA b−P(b−a)|) = ${fmt(b.MA)} kgf·cm<br>Vac = ${fmt(b.VH)} kgf；Vbc = |HB s−VB c| = ${fmt(b.VC)} kgf<br>斷面 A = ${fmt(b.s.Ax)} cm²；Ix = ${fmt(b.s.Ix)} cm⁴；rmin = ${fmt(b.r,4)} cm<br>斜桿 KL/r = ${fmt(b.sl)}；Fa = ${fmt(b.comp.Fa)} kgf/cm²<br>Ft = Fb = 0.6Fy；Fv = 0.4Fy<br>角鋼彎曲應力：M/√2 × (1/Su + 1/Sv)<br>自訂斷面：M/Sx<br>AC：N/(A Ft) + fb/Fb ≤ 1<br>BC：N/(A Fa) + fb/Fb ≤ 1；剪力：V/(Aw Fv) ≤ 1</div><p>保留原程式線性互制；未計彎矩放大、側扭挫屈、扭轉、焊縫及角鋼連接偏心。</p>`);
 html+=traceSection('05　錨栓個別檢核與未涵蓋項目',`<div class="formula">Ta群 = ${p.anchorN} × ${p.anchorT} / ${p.anchorSF} = ${fmt(b.Ta)} kgf<br>Va群 = ${p.anchorN} × ${p.anchorV} / ${p.anchorSF} = ${fmt(b.Va)} kgf<br>A 點：T = ${fmt(b.HB)}；V = ${fmt(Math.abs(b.VA))} kgf<br>B 點：V = ${fmt(Math.abs(b.VB))} kgf<br>原合力比 √(HA²+VA²)/√(Ta群²+Va群²) = ${fmt(b.oldResultant,4)}（僅追溯，不判 OK）<br>另列線性拉剪需求 T/Ta + V/Va = ${fmt(b.linearAnchor,4)}（非特定產品驗證）</div><p>拉剪互制須採產品評估與適用設計方法。混凝土錐狀破壞、劈裂、拉拔、邊距／群效應、撬力及 B 點承壓仍須另外檢核。</p>`);}
 html+=traceSection('06　原整架試驗外插參考（不列安全判定）',`<div class="formula">P舊參考 = [8.7 − 0.1(N−10)] × 1000 / (4×2.5) = ${fmt(r.empirical)} kgf/支柱<br>本次 P = ${fmt(r.P)} kgf/支柱</div><p>資料源為原碼所引十層單架間極限載重 8.7 t，未確認試驗架型、邊界條件與外插適用範圍；不得視為本案整體容許承載。</p>`);$('trace').innerHTML=html;}
 document.querySelectorAll('nav button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.tab-panel').forEach(x=>x.hidden=x.id!==btn.dataset.tab);});$('reset').onclick=()=>{if(!confirm('重設為預設範例？目前輸入的參數將被取代。'))return;current={...DEFAULTS};build();};$('print').onclick=()=>{if(last.errors.length)return;document.querySelectorAll('details').forEach(d=>d.open=true);$('print-inputs').innerHTML='<h2>輸入參數紀錄</h2><table><tbody>'+Object.entries(current).filter(([k])=>labels[k]).map(([k,v])=>`<tr><th>${labels[k]}</th><td>${typeof v==='boolean'?(v?'已確認':'未確認'):(document.getElementById(k)?.tagName==='SELECT'?document.getElementById(k).selectedOptions[0].textContent:v)}</td></tr>`).join('')+'</tbody></table><p>規範：國土署《建築物耐風設計規範及解說》104 年施行版含 103.12.03 修正；查核 2026-10-01。原碼 FormMain.vb 更新至 2016-08-15。工程適用範圍與未涵蓋項目詳網頁「原始解析與依據」。</p>';window.print();};build();
if(document.modelContext?.registerTool){
 const controller=new AbortController();window.addEventListener('pagehide',()=>controller.abort(),{once:true});
 const result=()=>({errors:last.errors,checks:last.rows?.map(({name,ratio})=>({name,ratio})),windForce:last.w?.F,totalLoad:last.WT,scope:'構件試算，不含整體穩定與完整錨栓設計'});
 const registrations=[{name:'read_scaffold_analysis',title:'讀取施工架試算',description:'讀取目前參數、風力與構件使用比。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return {parameters:{...current},...result()};}},{name:'configure_scaffold_analysis',title:'調整施工架試算參數',description:'批次調整畫面中可編輯的數值參數並即時計算，不核准設計或施工。',inputSchema:{type:'object',properties:Object.fromEntries(Object.entries(DEFAULTS).filter(([k,v])=>typeof v==='number'&&k!=='section').map(([k])=>[k,{type:'number',description:labels[k]||k}])),additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('參數必須為物件');for(const [k,v]of Object.entries(input))if(typeof DEFAULTS[k]!=='number'||k==='section'||!Number.isFinite(v))throw Error('無效數值參數：'+k);const next={...current,...input},r=calculate(next,SECTIONS);if(r.errors.length)throw Error(r.errors.join('；'));current=next;build();return result();}}];for(const t of registrations)try{Promise.resolve(document.modelContext.registerTool(t,{signal:controller.signal})).catch(()=>{});}catch{}}
$('exportWord').onclick=async()=>{
 const button=$('exportWord'),status=$('wordStatus');
 const p={...current},r=calculate(p,SECTIONS);
 if(r.errors.length){status.textContent='請先修正輸入參數';return;}
 button.disabled=true;status.textContent='產生 Word 中…';
 try{
  // Snapshot visible input values and the current complete calculation trace.
  const inputs=Object.keys(current).filter(k=>$(k)&&labels[k]).map(k=>{const el=$(k);const value=el.type==='checkbox'?(el.checked?'已確認':'未確認'):el.tagName==='SELECT'?el.selectedOptions[0].textContent:el.value;return [labels[k],value,el.closest('.field')?.querySelector('.unit')?.textContent||'—'];});
  inputs.unshift(['三角托架計算',p.bracket?'啟用':'停用','—']);
  const blocks=Array.from($('trace').querySelectorAll('details')).map(d=>({title:d.querySelector('summary').textContent,parts:Array.from(d.children).filter(x=>x.tagName!=='SUMMARY').map(x=>{const copy=x.cloneNode(true);copy.querySelectorAll('br').forEach(br=>br.replaceWith('\n'));return {kind:x.classList.contains('formula')?'formula':'paragraph',text:copy.textContent.trim()};})}));
  const date=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Taipei'}).format(new Date());
  const documentFile=ScaffoldWord.makeReport({p,r,inputs,blocks,date,example:false},docx);
  const blob=await docx.Packer.toBlob(documentFile);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`施工鷹架詳細計算書_${date}.docx`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);status.textContent='Word 已匯出';
 }catch(e){status.textContent='匯出失敗：'+e.message;}finally{button.disabled=false;}
};

const tabButtons=Array.from(document.querySelectorAll('nav button'));
function syncTabs(){tabButtons.forEach((b,i)=>{const selected=b.classList.contains('active');b.setAttribute('role','tab');b.setAttribute('aria-selected',String(selected));b.setAttribute('aria-controls',b.dataset.tab);b.id='tab-'+b.dataset.tab;b.tabIndex=selected?0:-1;const panel=$(b.dataset.tab);panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby',b.id);});}
tabButtons.forEach((b,i)=>{b.addEventListener('click',syncTabs);b.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabButtons.length;if(e.key==='ArrowLeft')next=(i+tabButtons.length-1)%tabButtons.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabButtons.length-1;if(next!==undefined){e.preventDefault();tabButtons[next].click();tabButtons[next].focus();}});});syncTabs();

// Responsive workspace views. Desktop keeps parameters and results side by side.
function setWorkspaceView(view){document.body.dataset.view=view;document.querySelectorAll('.view-switch button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));}
document.querySelectorAll('.view-switch button').forEach(b=>b.addEventListener('click',()=>{setWorkspaceView(b.dataset.view);window.scrollTo({top:0,behavior:'smooth'});}));
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>setWorkspaceView('inputs')));
document.querySelector('.result-top a').addEventListener('click',()=>setWorkspaceView('report'));
tabButtons.forEach((b,i)=>b.addEventListener('keydown',e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const n=(i+(e.key==='ArrowDown'?1:-1)+tabButtons.length)%tabButtons.length;tabButtons[n].click();tabButtons[n].focus();}}));

// The handbook is kept outside the calculation inputs and export trace.
const helpSections=Array.from(document.querySelectorAll('.help-section'));
function filterHelp(){const q=$('helpSearch').value.trim().toLocaleLowerCase();let count=0;for(const section of helpSections){const matches=!q||section.textContent.toLocaleLowerCase().includes(q);section.hidden=!matches;if(matches){count++;if(q)section.open=true;}}$('helpStatus').textContent=q?(count?`找到 ${count} 個相關章節`:'找不到相關內容，請換個關鍵字。'):`共 ${helpSections.length} 個章節，點選標題展開。`;}
$('helpSearch').addEventListener('input',filterHelp);
$('helpClear').addEventListener('click',()=>{$('helpSearch').value='';filterHelp();$('helpSearch').focus();});
$('helpExpand').addEventListener('click',()=>helpSections.forEach(s=>{if(!s.hidden)s.open=true;}));
$('helpCollapse').addEventListener('click',()=>helpSections.forEach(s=>s.open=false));
function syncHelpLayout(){const active=document.querySelector('nav button.active')?.dataset.tab==='help';document.body.classList.toggle('help-active',active);}
tabButtons.forEach(b=>b.addEventListener('click',syncHelpLayout));
function openHelpFromHash(){if(location.hash==='#help'){document.querySelector('nav button[data-tab="help"]').click();}}
window.addEventListener('hashchange',openHelpFromHash);openHelpFromHash();


// Complete teaching snapshots keep both cases reproducible.
const SCAFFOLD_EXAMPLES={"A":{"top":20,"base":0,"step":1.725,"bay":180,"width":90,"offset":20,"d":42.7,"t":2.4,"loss":0.3,"dd":21.7,"dt":1.9,"deck":60,"weightMode":"auto","weight":40,"dl":100,"ll":200,"work":2,"fy":2300,"E":2040000,"k":1,"unbraced":1,"reduction":1,"terrain":"B","v":42.5,"importance":1,"kzt":1,"gmode":"fixed","fn":1,"beta":0.01,"windB":20,"windL":10,"gm":1.88,"cover":0.5,"windMode":"auto","cf":1.6,"netC":2.5,"phiMode":"auto","phi":0.5,"tieX":3.6,"tieY":3.5,"tieT":883,"tieC":883,"windConfirmed":false,"capacityConfirmed":false,"bracket":true,"B":115,"D":65,"spacing":180,"pieces":1,"section":9,"bracketFy":2300,"bracketK":1,"customA":12.69,"customI":64.4,"customS":12.1,"customAw":6.75,"customR":1.45,"anchorT":2465,"anchorV":3460,"anchorSF":2,"anchorN":1},"B":{"top":20,"base":0,"step":1.725,"bay":180,"width":90,"offset":20,"d":42.7,"t":2.4,"loss":0.3,"dd":21.7,"dt":1.9,"deck":60,"weightMode":"auto","weight":40,"dl":100,"ll":200,"work":2,"fy":2300,"E":2040000,"k":1,"unbraced":1,"reduction":1,"terrain":"B","v":42.5,"importance":1,"kzt":1,"gmode":"fixed","fn":1,"beta":0.01,"windB":20,"windL":10,"gm":1.88,"cover":0.5,"windMode":"auto","cf":1.6,"netC":2.5,"phiMode":"auto","phi":0.5,"tieX":1.8,"tieY":3.5,"tieT":883,"tieC":883,"windConfirmed":false,"capacityConfirmed":false,"bracket":true,"B":115,"D":65,"spacing":180,"pieces":1,"section":9,"bracketFy":2300,"bracketK":1,"customA":12.69,"customI":64.4,"customS":12.1,"customAw":6.75,"customR":1.45,"anchorT":2465,"anchorV":3460,"anchorSF":2,"anchorN":1}};
document.querySelectorAll("[data-scaffold-example]").forEach(button=>button.addEventListener("click",()=>{const key=button.dataset.scaffoldExample;const next={...SCAFFOLD_EXAMPLES[key]};if(calculate(next,SECTIONS).errors.length)return;if(!confirm("載入範例 "+key+" 將取代目前全部參數。請先匯出要保留的計算書。確定載入？"))return;current=next;build();document.querySelector('nav button[data-tab="geometry"]').click();$("exampleStatus").hidden=false;$("exampleStatus").textContent="已載入教學範例 "+key+"；工程確認框保持未勾選。後續修改會即時更新結果。";window.scrollTo({top:0,behavior:"smooth"});}));
