/* Calculation engine. Units: cm, m, kgf; source map in method.html. */
let activeTrace=null;function step(title,formula,data,unit='',condition='',source='原引擎與原計算書章節'){if(activeTrace)activeTrace.push({title,formula,data,unit,condition,source});}const TERRAIN={A:{alpha:.32,zg:500,b:.45,c:.45,l:55,e:.5,zmin:18},B:{alpha:.25,zg:400,b:.62,c:.30,l:98,e:.33,zmin:9},C:{alpha:.15,zg:300,b:.94,c:.20,l:152,e:.20,zmin:4.5}};
const DEFAULTS={top:20,base:0,step:1.725,bay:180,width:90,offset:20,d:42.7,t:2.4,loss:.3,dd:21.7,dt:1.9,deck:60,weightMode:'auto',weight:40,dl:100,ll:200,work:2,fy:2300,E:2040000,k:1,unbraced:1,reduction:1,terrain:'B',v:42.5,importance:1,kzt:1,gmode:'fixed',fn:1,beta:.01,windB:20,windL:10,gm:1.88,cover:.5,windMode:'auto',cf:1.6,netC:2.5,phiMode:'auto',phi:.5,tieX:3.6,tieY:3.5,tieT:883,tieC:883,windConfirmed:false,capacityConfirmed:false,bracket:true,B:115,D:65,spacing:180,pieces:1,section:9,bracketFy:2300,bracketK:1,customA:12.69,customI:64.4,customS:12.1,customAw:6.75,customR:1.45,anchorT:2465,anchorV:3460,anchorSF:2,anchorN:1};
function tube(d,t){const input={d,t};d/=10;t/=10;const A=Math.PI/4*(d*d-(d-2*t)**2),I=Math.PI/64*(d**4-(d-2*t)**4);const r=Math.sqrt(I/A),Z=2*I/d;step('圓管實際斷面','d,t:mm÷10→cm；A=π/4[d²-(d-2t)²];I=π/64[d⁴-(d-2t)⁴];r=√(I/A);Z=2I/d',{input,d,t,A,I,r,Z},'cm、cm²、cm⁴、cm³','名義/斜撐/腐蝕後按實際呼叫輸入分別記錄');return {A,I,r,Z};}
function compression(lambda,fy,E){const Cc=Math.sqrt(2*Math.PI**2*E/fy),x=lambda/Cc;const Fa=x<1?(1-x*x/2)*fy/(5/3+3*x/8-x**3/8):12/23*Math.PI**2*E/lambda**2;step('ASD軸壓分支','Cc=√(2π²E/Fy);x=lambda/Cc；x<1:Fa=(1-x²/2)Fy/(5/3+3x/8-x³/8)；else:Fa=12π²E/(23lambda²)',{lambda,fy,E,Cc,x,Fa},'kgf/cm²','本次branch='+ (x<1?'非彈性':'彈性')+'；使用原算法');return {Cc,Fa};}
function validate(p){const errors=[];const enums={terrain:['A','B','C'],weightMode:['auto','manual'],gmode:['fixed','rigid','flexible','manual'],windMode:['auto','manual','net'],phiMode:['auto','manual']};for(const [k,values]of Object.entries(enums))if(!values.includes(p[k]))errors.push(k+' 選項無效');const nonneg=['base','offset','loss','dl','ll','cover'];const positives=['top','step','bay','width','d','t','dd','dt','deck','weight','fy','E','k','unbraced','reduction','v','importance','kzt','fn','beta','windB','windL','gm','cf','netC','phi','tieX','tieY','tieT','tieC'];if(p.bracket)positives.push('B','D','spacing','pieces','bracketFy','bracketK','customA','customI','customS','customAw','customR','anchorT','anchorV','anchorSF','anchorN');for(const k of positives)if(!Number.isFinite(p[k])||p[k]<=0)errors.push(`${k} 必須大於 0`);for(const k of nonneg)if(!Number.isFinite(p[k])||p[k]<0)errors.push(`${k} 不得為負值`);if(!(p.top>p.base))errors.push('頂端高程必須大於起始高程');if(p.t<=p.loss||2*p.t>=p.d)errors.push('鋼管厚度需大於腐蝕扣減，且小於半徑');if(2*p.dt>=p.dd)errors.push('斜撐管厚度不得大於半徑');if(p.reduction>1||p.cover>1||p.phi>1)errors.push('折減率、遮網實體率與總實體率不得大於 1');if(p.kzt<1)errors.push('Kzt 不得小於 1');if(p.fn<.01)errors.push('自然頻率 fn 不得小於 0.01 Hz');if(p.width<=2*p.d/10||p.bay<=2*p.d/10)errors.push('立框間距與寬度需大於兩倍鋼管外徑');if(p.section!=='custom'&&(!Number.isInteger(Number(p.section))||Number(p.section)<0||Number(p.section)>22))errors.push('托架斷面選項無效');if(p.beta>=1)errors.push('阻尼比 β 必須小於 1');if(p.importance<.9||p.importance>1.1)errors.push('用途係數 I 僅支援 0.9–1.1，不以工期自動折減');if(!Number.isInteger(p.work)||p.work<0)errors.push('作業層數需為非負整數');if(p.bracket&&(!Number.isInteger(p.pieces)||!Number.isInteger(p.anchorN)))errors.push('角鋼數與錨栓數需為整數');if(p.bracket&&p.offset+p.width>p.B)errors.push('兩支立柱的受力位置必須位於托架範圍內（a＋寬 ≤ B）');if(p.gmode==='fixed'&&p.fn<1)errors.push('fn < 1 Hz 請選用柔性計算或輸入經分析的 Gf');if(p.gmode==='rigid'&&p.fn<1)errors.push('普通結構公式需要 fn ≥ 1 Hz');if(!TERRAIN[p.terrain])errors.push('地況無效');if(p.top>300)errors.push('本工具高度上限 300 m；更高結構需另行分析');if(p.top>p.base&&p.work>Math.ceil((p.top-p.base)/p.step-1e-10))errors.push('作業層數不可超過搭設層數');return errors;}
function gust(p){const t=TERRAIN[p.terrain],h=p.top,zbar=Math.max(.6*h,t.zmin),Lz=t.l*(zbar/10)**t.e,Iz=t.c*(10/zbar)**(1/6),Q=Math.sqrt(1/(1+.63*((p.windB+h)/Lz)**.63));let G=1.88,details={zbar,Lz,Iz,Q};if(p.gmode==='manual')G=p.gm;if(p.gmode==='rigid')G=1.927*(1+1.7*3.4*Iz*Q)/(1+1.7*3.4*Iz);if(p.gmode==='flexible'){const V=t.b*(zbar/10)**t.alpha*p.v,N=p.fn*Lz/V,Rn=7.47*N/(1+10.3*N)**(5/3);const rj=x=>{const value=x<1e-4?1-2*x/3+x*x/3:1/x+Math.expm1(-2*x)/(2*x*x);step('柔性陣風Rj實際分支','x<1e-4:1-2x/3+x²/3；else:1/x+expm1(-2x)/(2x²)',{x,value},'無因次',x<1e-4?'小x展開':'expm1原式','原風規範2.7與本程式数值穩定分支');return value;};const Rh=rj(4.6*p.fn*h/V),Rb=rj(4.6*p.fn*p.windB/V),Rl=rj(15.4*p.fn*p.windL/V),R=Math.sqrt(Rn*Rh*Rb*(.53+.47*Rl)/p.beta),gr=Math.sqrt(2*Math.log(3600*p.fn))+.577/Math.sqrt(2*Math.log(3600*p.fn));G=1.927*(1+1.7*Iz*Math.sqrt(3.4**2*Q**2+gr**2*R**2))/(1+1.7*3.4*Iz);Object.assign(details,{V,N,Rn,Rh,Rb,Rl,R,gr});}step('本次地況查表與陣風係數','zbar=max(.6h,zmin);Lz=l(zbar/10)^e;Iz=c(10/zbar)^(1/6);Q=√[1/(1+.63((B+h)/Lz)^.63)]；G依本次mode',{terrain:p.terrain,terrainRow:t,mode:p.gmode,h,zbar,Lz,Iz,Q,G,...details,input:{fn:p.fn,beta:p.beta,V:p.v,B:p.windB,L:p.windL,gm:p.gm}},'m、m/s、Hz；G無因次','fixed=1.88；manual=gm；rigid=1.927(1+1.7·3.4IzQ)/(1+1.7·3.4Iz)；flexible用記錄V/N/Rn/Rh/Rb/Rl/R/gr','原風規範表2.2 地況'+p.terrain+'行，alpha/zg/b/c/l/e/zmin欄；陣風2.7');return {G,...details};}
function linear(x,xx,yy){if(x<=xx[0]){step('表2.10低端查值','x<=首列，採首列',{x,xx,yy,index:0,value:yy[0]},'無因次','端點夾限','原風規範表2.10及原內建列');return yy[0];}for(let i=1;i<xx.length;i++)if(x<=xx[i]){const weight=(x-xx[i-1])/(xx[i]-xx[i-1]),value=yy[i-1]+weight*(yy[i]-yy[i-1]);step('表2.10實際線性內插','y=y0+(x-x0)/(x1-x0)(y1-y0)',{x,xx,yy,rows:[i-1,i],x0:xx[i-1],x1:xx[i],y0:yy[i-1],y1:yy[i],weight,value},'無因次','原列間線性内插','原風規範表2.10原內建列/欄');return value;}step('表2.10高端查值','x>尾列，採尾列',{x,xx,yy,index:xx.length-1,value:yy.at(-1)},'無因次','端點夾限','原風規範表2.10');return yy.at(-1);}
function wind(p,z,g){const t=TERRAIN[p.terrain],Kz=2.774*(Math.max(z,5)/t.zg)**(2*t.alpha),q=.06*Kz*p.kzt*(p.importance*p.v)**2,hs=p.step*100,dc=p.d/10,dd=p.dd/10;const raw=(p.cover===0?(dc*(p.bay*2+hs*2)+dd*182.4*4+5*p.bay):(dc*(p.bay+hs)+dd*182.4*2+4*p.bay))/(p.bay*hs);const steel=Math.min(1,raw),phi=p.phiMode==='manual'?p.phi:p.cover+(1-p.cover)*steel;const solid=phi>.7;let cf,areaFactor,method;const j=phi<.1?0:phi<.3?1:2;
 if(p.windMode==='net'){cf=p.netC;areaFactor=1;method='經專案分析之淨風壓係數 Cnet（已含陣風）';}
 else if(p.windMode==='manual'){cf=p.cf;areaFactor=phi;method='自訂 Cf × 實體投影面積';}
 else if(solid){const ground=p.base<.25*(p.top-p.base),ratio=ground?(p.top-p.base)/p.windB:Math.max(p.top-p.base,p.windB)/Math.min(p.top-p.base,p.windB);cf=linear(ratio,ground?[3,5,8,10,20,30,40]:[6,10,16,20,40,60,80],[1.2,1.3,1.4,1.5,1.75,1.85,2]);areaFactor=1;method='表 2.10 實體標示物類比（全投影面積）';}
 else {cf=p.cover===0?((p.d/1000*Math.sqrt(q)<=1.70)?[1.2,1.3,1.5]:[.8,.9,1.1])[j]:[2,1.8,1.6][j];areaFactor=phi;method=p.cover===0?'表 2.11 圓管格架類比':'表 2.11 平邊格架類比';}
 const pressure=q*(p.windMode==='net'?1:g.G)*cf*areaFactor,area=p.tieX*p.tieY,F=pressure*area;
 // Historical reference, ordinary structure branch at the same elevation.
 const oldPhi=p.cover===0?steel:p.cover+(1-p.cover)*steel,oldj=oldPhi<.1?0:oldPhi<=.29?1:2,oldCf=p.cover===0?((p.d/1000*Math.sqrt(q/p.kzt)<=1.5)?[1.2,1.3,1.5]:[.8,.9,1.1])[oldj]:[2,1.8,1.6][oldj],oldF=q/p.kzt*(p.cover>.7?(1.77*1.3+.75):1.77*oldCf)*oldPhi*area;
 step('本次高度風壓與Cf查表','Kz=2.774[max(z,5)/zg]^(2alpha);q=.06Kz Kzt(IV)²;raw=原構件投影面積/(bay hs);steel=min(1,raw);phi=manual或cover+(1-cover)steel;p=q·G·Cf·areaFactor（net不用G）;F=p tieX tieY',{z,terrain:p.terrain,terrainRow:t,Kz,q,hs,dc,dd,raw,steel,phi,j,solid,mode:p.windMode,cf,areaFactor,pressure,area,F,method,inputs:{bay:p.bay,step:p.step,cover:p.cover,phiMode:p.phiMode,manualPhi:p.phi,cf:p.cf,netC:p.netC,top:p.top,base:p.base,windB:p.windB,d:p.d,kzt:p.kzt,importance:p.importance,v:p.v,tieX:p.tieX,tieY:p.tieY,G:g.G},table211:{columns:['phi<.1','.1<=phi<.3','phi>=.3'],flat:[2,1.8,1.6],roundLow:[1.2,1.3,1.5],roundHigh:[.8,.9,1.1],roundCriterion:p.d/1000*Math.sqrt(q),threshold:1.70},historical:{oldPhi,oldj,oldCf,oldF,qWithoutKzt:q/p.kzt,roundCriterion:p.d/1000*Math.sqrt(q/p.kzt),threshold:1.5}},'kgf/m²、kgf、m、cm','solid=phi>.7；表2.11原j分箱与直徑·sqrt(q)<=1.70判圓管行；manual/net不查Cf表。历史oldF單列參考，保持.29/1.5门檻與新計算不同。','原風規範表2.2/2.10/2.11；與原VB歷史參考對照');return {z,Kz,q,steel,raw,phi,cf,areaFactor,pressure,area,F,method,oldF};}
function calculate(p,sections){activeTrace=[];const errors=validate(p);if(errors.length){activeTrace=null;return {errors};}const N=Math.ceil((p.top-p.base)/p.step-1e-10),nom=tube(p.d,p.t),diag=tube(p.dd,p.dt),sec=tube(p.d,p.t-p.loss);const qw1=.78*nom.A*p.step*2,qw2=.78*nom.A*(p.width/100-2*p.d/1000)*2,qw3=.78*nom.A*(p.bay/100-2*p.d/1000)*2,frame=qw1+qw2+qw3+2.5,deckW=17*p.deck/60,brace=.78*diag.A*1.829*4+3.2;const rawW=frame+deckW+brace; // VB CInt uses ties-to-even
 const roundEven=x=>Math.abs(x%1-.5)<1e-9?(Math.floor(x)%2===0?Math.floor(x):Math.ceil(x)):Math.round(x);
 const W0=p.weightMode==='auto'?roundEven(rawW):p.weight,WD=N*W0,WL=p.work*(p.dl+p.ll),WT=WD+WL,P=WT/2,lambda=p.k*p.step*100*p.unbraced/sec.r,{Cc,Fa}=compression(lambda,p.fy,p.E),allow=Fa*p.reduction,fa=P/sec.A,g=gust(p),w=wind(p,p.top,g),rows=[];
 const add=(name,demand,capacity,unit,note,group='main')=>{step(name,'D/C=demand/capacity',{demand,capacity,ratio:demand/capacity,pass:demand<=capacity,group},unit,note);rows.push({name,demand,capacity,unit,ratio:demand/capacity,note,group});};
 add('立柱軸壓應力',fa,allow,'kgf/cm²','有效厚度 t − 腐蝕扣減；原 ASD 公式');add('壁連桿抗拉',w.F,p.tieT,'kgf','包含連接、錨定之整組容許拉力');add('壁連桿抗壓',w.F,p.tieC,'kgf','反向風；需計入桿件挫屈與接頭');
 step('架重、層數、工作荷重與立柱需求','N=ceil((top-base)/step-1e-10);qw1=.78Anom step·2;qw2=.78Anom(width/100-2d/1000)·2;qw3=.78Anom(bay/100-2d/1000)·2;frame=qw1+qw2+qw3+2.5;deckW=17deck/60;brace=.78Adiag·1.829·4+3.2;rawW=sum;W0=auto ties-to-even或manual；WD=NW0;WL=work(dl+ll);P=(WD+WL)/2;lambda=k step·100 unbraced/r;fa=P/A;allow=Fa reduction',{input:p,N,ceilArgument:(p.top-p.base)/p.step-1e-10,nom,diag,sec,qw1,qw2,qw3,frame,deckW,brace,rawW,W0,rounding:{floor:Math.floor(rawW),ceil:Math.ceil(rawW),fraction:rawW%1,tie:Math.abs(rawW%1-.5)<1e-9,floorEven:Math.floor(rawW)%2===0,mode:p.weightMode},WD,WL,WT,P,lambda,Cc,Fa,allow,fa},'kgf、kgf/cm²、cm、m','同一計算實際W0；原VB CInt銀行家取整，半數容差1e-9；ceil層數另含1e-10。名義管算自重，腐蝕管算容量。');let bracket=null;if(p.bracket){const custom=p.section==='custom',s=custom?{Ax:p.customA,Ix:p.customI,Sx:p.customS,Ash:p.customAw,Iv:p.customR**2*p.customA}:sections[Number(p.section)];const a=p.offset,b=a+p.width,B=p.B,D=p.D,L=Math.hypot(B,D),co=B/L,si=D/L,KGB=p.spacing/p.bay/p.pieces,Px=P*KGB,HB=Px*(a+b)/D,vbNumerator=(HB*L**3*si*co/3+HB*D*B*B/2-Px*(a**3+b**3)/6),vbDenominator=(L**3*co**2/3+B**3/3),VB=vbNumerator/vbDenominator,VA=2*Px-VB,NC=HB*co+VB*si,MC=Math.abs(VB*B-HB*D),MA=Math.max(Math.abs(VA*a),Math.abs(VA*B-Px*(B-a)-Px*(B-b)),Math.abs(VA*b-Px*(b-a))),VC=Math.abs(HB*si-VB*co),VH=Math.max(Math.abs(VA),Math.abs(Px-VA),Math.abs(2*Px-VA)),r=custom?p.customR:Math.sqrt(s.Iv/s.Ax),sl=p.bracketK*L/r,comp=compression(sl,p.bracketFy,p.E),Fb=.6*p.bracketFy,Ft=Fb,Fv=.4*p.bracketFy,bend=M=>{const stress=custom?M/s.Sx:M/Math.sqrt(2)*(1/s.Su+1/s.Sv);step('托架實際彎曲應力','custom:M/Sx；角鋼:M/√2(1/Su+1/Sv)',{custom,M,section:s,stress},'kgf/cm²','角钢u/v雙主軸，custom单軸，保留原模型','本次sections.js原斷面列或custom輸入');return stress;},ra=HB/s.Ax/Ft+bend(MA)/Fb,rc=NC/s.Ax/comp.Fa+bend(MC)/Fb;
 add('托架 AC 拉彎互制',ra,1,'比值','原線性應力疊加法','bracket');add('托架 AC 剪應力',VH/s.Ash,Fv,'kgf/cm²','按剪力面積 Aw','bracket');add('托架 BC 壓彎互制',rc,1,'比值','原線性應力疊加法；非二階分析','bracket');add('托架 BC 剪應力',VC/s.Ash,Fv,'kgf/cm²','按剪力面積 Aw','bracket');
 const Ta=p.anchorT/p.anchorSF*p.anchorN,Va=p.anchorV/p.anchorSF*p.anchorN;add('A 點錨栓拉力',HB,Ta,'kgf','各端每一片托架之錨栓群','anchor');add('A 點錨栓剪力',Math.abs(VA),Va,'kgf','均勻分配假設','anchor');add('B 點錨栓剪力',Math.abs(VB),Va,'kgf','均勻分配假設','anchor');step('托架冗餘反力、包絡與断面查表','a=offset;b=a+width;L=hypot(B,D);co=B/L;si=D/L;KGB=spacing/bay/pieces;Px=P KGB;HB=Px(a+b)/D;VB=Numerator/Denominator;VA=2Px-VB;NC=HB co+VB si;MC=abs(VB B-HB D);MA=max(abs(VA a),abs(VA B-Px(B-a)-Px(B-b)),abs(VA b-Px(b-a)));VC=abs(HB si-VB co);VH=max(abs(VA),abs(Px-VA),abs(2Px-VA));lambda=K L/r;Ta=anchorT/SF·N;Va=anchorV/SF·N',{custom,rowIndex:p.section,s,a,b,B,D,L,co,si,KGB,Px,HB,vbNumerator,vbDenominator,VB,VA,NC,MC,MA,maCandidates:[Math.abs(VA*a),Math.abs(VA*B-Px*(B-a)-Px*(B-b)),Math.abs(VA*b-Px*(b-a))],VC,VH,vhCandidates:[Math.abs(VA),Math.abs(Px-VA),Math.abs(2*Px-VA)],r,sl,comp,Fb,Ft,Fv,ra,rc,Ta,Va,oldResultant:Math.hypot(HB,VA)/Math.hypot(Ta,Va),linearAnchor:HB/Ta+Math.abs(VA)/Va},'cm、kgf、kgf·cm、kgf/cm²','等EI/忽略軸向變形的原冗餘反力；錨栓分別承載與互制诊断分列，互制非特定產品認證。','本次sections.js原23行rowIndex（0起），Ax/Ix/Sx/Ash/Iv/Su/Sv；custom沒有查表修正。');bracket={vbNumerator,vbDenominator,co,si,Fb,Ft,Fv,ra,rc,s,a,b,B,D,L,Px,KGB,HB,VA,VB,NC,MC,MA,VC,VH,r,sl,comp,Ta,Va,oldResultant:Math.hypot(HB,VA)/Math.hypot(Ta,Va),linearAnchor:HB/Ta+Math.abs(VA)/Va};}
 const profile=Array.from({length:21},(_,i)=>wind(p,p.base+(p.top-p.base)*i/20,g)),worst=rows.reduce((a,b)=>b.ratio>a.ratio?b:a),warnings=[];if(w.raw>1)warnings.push('原投影面積估算超出總面積，已上限為 1；請改用實測實體率。');if(lambda>200)warnings.push('立柱 KL/r > 200：超出本工具一般受壓構材檢核範圍，需重新配置側向支撐。');if(bracket&&bracket.sl>200)warnings.push('斜桿 KL/r > 200，須另行確認適用性。');if(p.gmode==='flexible'&&p.fn>=1)warnings.push('fn ≥ 1 Hz；目前仍採柔性公式，請確認振態設定。');if(p.step!==1.725&&p.weightMode==='auto')warnings.push('層高已調整；斜撐與踏板重量仍採原標準模組估算，宜改輸入實測組重。');if(!p.windConfirmed)warnings.push('風力係數、現地地況及施工架與建築物之互制尚未確認。');if(!p.capacityConfirmed)warnings.push('壁連桿及錨栓容量為示範值，尚未由產品試驗與基材條件確認。');if(!rows.every(x=>Number.isFinite(x.ratio))||!Number.isFinite(w.F)||!Number.isFinite(g.G))return {errors:['參數超出可計算範圍，請檢查尺寸、材料與動力參數']};const trace=activeTrace;activeTrace=null;return {trace,errors:[],N,nom,sec,frame,deckW,brace,rawW,W0,WD,WL,WT,P,lambda,Cc,Fa,allow,fa,g,w,rows,bracket,profile,worst,warnings,empirical:(8.7-.1*(N-10))*1000/(4*2.5)};}
if(typeof module!=='undefined')module.exports={DEFAULTS,TERRAIN,tube,compression,gust,wind,calculate,validate};


