/* Calculation engine. Units: cm, m, kgf; source map in method.html. */
const TERRAIN={A:{alpha:.32,zg:500,b:.45,c:.45,l:55,e:.5,zmin:18},B:{alpha:.25,zg:400,b:.62,c:.30,l:98,e:.33,zmin:9},C:{alpha:.15,zg:300,b:.94,c:.20,l:152,e:.20,zmin:4.5}};
const DEFAULTS={top:20,base:0,step:1.725,bay:180,width:90,offset:20,d:42.7,t:2.4,loss:.3,dd:21.7,dt:1.9,deck:60,weightMode:'auto',weight:40,dl:100,ll:200,work:2,fy:2300,E:2040000,k:1,unbraced:1,reduction:1,terrain:'B',v:42.5,importance:1,kzt:1,gmode:'fixed',fn:1,beta:.01,windB:20,windL:10,gm:1.88,cover:.5,windMode:'auto',cf:1.6,netC:2.5,phiMode:'auto',phi:.5,tieX:3.6,tieY:3.5,tieT:883,tieC:883,windConfirmed:false,capacityConfirmed:false,bracket:true,B:115,D:65,spacing:180,pieces:1,section:9,bracketFy:2300,bracketK:1,customA:12.69,customI:64.4,customS:12.1,customAw:6.75,customR:1.45,anchorT:2465,anchorV:3460,anchorSF:2,anchorN:1};
function tube(d,t){d/=10;t/=10;const A=Math.PI/4*(d*d-(d-2*t)**2),I=Math.PI/64*(d**4-(d-2*t)**4);return {A,I,r:Math.sqrt(I/A),Z:2*I/d};}
function compression(lambda,fy,E){const Cc=Math.sqrt(2*Math.PI**2*E/fy),x=lambda/Cc;return {Cc,Fa:x<1?(1-x*x/2)*fy/(5/3+3*x/8-x**3/8):12/23*Math.PI**2*E/lambda**2};}
function validate(p){const errors=[];const nonneg=['base','offset','loss','dl','ll','cover'];const positives=['top','step','bay','width','d','t','dd','dt','deck','weight','fy','E','k','unbraced','reduction','v','importance','kzt','fn','beta','windB','windL','gm','cf','netC','phi','tieX','tieY','tieT','tieC'];if(p.bracket)positives.push('B','D','spacing','pieces','bracketFy','bracketK','customA','customI','customS','customAw','customR','anchorT','anchorV','anchorSF','anchorN');for(const k of positives)if(!Number.isFinite(p[k])||p[k]<=0)errors.push(`${k} 必須大於 0`);for(const k of nonneg)if(!Number.isFinite(p[k])||p[k]<0)errors.push(`${k} 不得為負值`);if(!(p.top>p.base))errors.push('頂端高程必須大於起始高程');if(p.t<=p.loss||2*p.t>=p.d)errors.push('鋼管厚度需大於腐蝕扣減，且小於半徑');if(2*p.dt>=p.dd)errors.push('斜撐管厚度不得大於半徑');if(p.reduction>1||p.cover>1||p.phi>1)errors.push('折減率、遮網實體率與總實體率不得大於 1');if(p.kzt<1)errors.push('Kzt 不得小於 1');if(p.fn<.01)errors.push('自然頻率 fn 不得小於 0.01 Hz');if(p.width<=2*p.d/10||p.bay<=2*p.d/10)errors.push('立框間距與寬度需大於兩倍鋼管外徑');if(p.section!=='custom'&&(!Number.isInteger(Number(p.section))||Number(p.section)<0||Number(p.section)>22))errors.push('托架斷面選項無效');if(p.beta>=1)errors.push('阻尼比 β 必須小於 1');if(p.importance<.9||p.importance>1.1)errors.push('用途係數 I 僅支援 0.9–1.1，不以工期自動折減');if(!Number.isInteger(p.work)||p.work<0)errors.push('作業層數需為非負整數');if(p.bracket&&(!Number.isInteger(p.pieces)||!Number.isInteger(p.anchorN)))errors.push('角鋼數與錨栓數需為整數');if(p.bracket&&p.offset+p.width>p.B)errors.push('兩支立柱的受力位置必須位於托架範圍內（a＋寬 ≤ B）');if(p.gmode==='fixed'&&p.fn<1)errors.push('fn < 1 Hz 請選用柔性計算或輸入經分析的 Gf');if(p.gmode==='rigid'&&p.fn<1)errors.push('普通結構公式需要 fn ≥ 1 Hz');if(!TERRAIN[p.terrain])errors.push('地況無效');if(p.top>300)errors.push('本工具高度上限 300 m；更高結構需另行分析');if(p.top>p.base&&p.work>Math.ceil((p.top-p.base)/p.step-1e-10))errors.push('作業層數不可超過搭設層數');return errors;}
function gust(p){const t=TERRAIN[p.terrain],h=p.top,zbar=Math.max(.6*h,t.zmin),Lz=t.l*(zbar/10)**t.e,Iz=t.c*(10/zbar)**(1/6),Q=Math.sqrt(1/(1+.63*((p.windB+h)/Lz)**.63));let G=1.88,details={zbar,Lz,Iz,Q};if(p.gmode==='manual')G=p.gm;if(p.gmode==='rigid')G=1.927*(1+1.7*3.4*Iz*Q)/(1+1.7*3.4*Iz);if(p.gmode==='flexible'){const V=t.b*(zbar/10)**t.alpha*p.v,N=p.fn*Lz/V,Rn=7.47*N/(1+10.3*N)**(5/3);const rj=x=>x<1e-4?1-2*x/3+x*x/3:1/x+Math.expm1(-2*x)/(2*x*x);const Rh=rj(4.6*p.fn*h/V),Rb=rj(4.6*p.fn*p.windB/V),Rl=rj(15.4*p.fn*p.windL/V),R=Math.sqrt(Rn*Rh*Rb*(.53+.47*Rl)/p.beta),gr=Math.sqrt(2*Math.log(3600*p.fn))+.577/Math.sqrt(2*Math.log(3600*p.fn));G=1.927*(1+1.7*Iz*Math.sqrt(3.4**2*Q**2+gr**2*R**2))/(1+1.7*3.4*Iz);Object.assign(details,{V,N,Rn,Rh,Rb,Rl,R,gr});}return {G,...details};}
function linear(x,xx,yy){if(x<=xx[0])return yy[0];for(let i=1;i<xx.length;i++)if(x<=xx[i])return yy[i-1]+(x-xx[i-1])/(xx[i]-xx[i-1])*(yy[i]-yy[i-1]);return yy.at(-1);}
function wind(p,z,g){const t=TERRAIN[p.terrain],Kz=2.774*(Math.max(z,5)/t.zg)**(2*t.alpha),q=.06*Kz*p.kzt*(p.importance*p.v)**2,hs=p.step*100,dc=p.d/10,dd=p.dd/10;const raw=(p.cover===0?(dc*(p.bay*2+hs*2)+dd*182.4*4+5*p.bay):(dc*(p.bay+hs)+dd*182.4*2+4*p.bay))/(p.bay*hs);const steel=Math.min(1,raw),phi=p.phiMode==='manual'?p.phi:p.cover+(1-p.cover)*steel;const solid=phi>.7;let cf,areaFactor,method;const j=phi<.1?0:phi<.3?1:2;
 if(p.windMode==='net'){cf=p.netC;areaFactor=1;method='經專案分析之淨風壓係數 Cnet（已含陣風）';}
 else if(p.windMode==='manual'){cf=p.cf;areaFactor=phi;method='自訂 Cf × 實體投影面積';}
 else if(solid){const ground=p.base<.25*(p.top-p.base),ratio=ground?(p.top-p.base)/p.windB:Math.max(p.top-p.base,p.windB)/Math.min(p.top-p.base,p.windB);cf=linear(ratio,ground?[3,5,8,10,20,30,40]:[6,10,16,20,40,60,80],[1.2,1.3,1.4,1.5,1.75,1.85,2]);areaFactor=1;method='表 2.10 實體標示物類比（全投影面積）';}
 else {cf=p.cover===0?((p.d/1000*Math.sqrt(q)<=1.70)?[1.2,1.3,1.5]:[.8,.9,1.1])[j]:[2,1.8,1.6][j];areaFactor=phi;method=p.cover===0?'表 2.11 圓管格架類比':'表 2.11 平邊格架類比';}
 const pressure=q*(p.windMode==='net'?1:g.G)*cf*areaFactor,area=p.tieX*p.tieY,F=pressure*area;
 // Historical reference, ordinary structure branch at the same elevation.
 const oldPhi=p.cover===0?steel:p.cover+(1-p.cover)*steel,oldj=oldPhi<.1?0:oldPhi<=.29?1:2,oldCf=p.cover===0?((p.d/1000*Math.sqrt(q/p.kzt)<=1.5)?[1.2,1.3,1.5]:[.8,.9,1.1])[oldj]:[2,1.8,1.6][oldj],oldF=q/p.kzt*(p.cover>.7?(1.77*1.3+.75):1.77*oldCf)*oldPhi*area;
 return {z,Kz,q,steel,raw,phi,cf,areaFactor,pressure,area,F,method,oldF};}
function calculate(p,sections){const errors=validate(p);if(errors.length)return {errors};const N=Math.ceil((p.top-p.base)/p.step-1e-10),nom=tube(p.d,p.t),diag=tube(p.dd,p.dt),sec=tube(p.d,p.t-p.loss);const qw1=.78*nom.A*p.step*2,qw2=.78*nom.A*(p.width/100-2*p.d/1000)*2,qw3=.78*nom.A*(p.bay/100-2*p.d/1000)*2,frame=qw1+qw2+qw3+2.5,deckW=17*p.deck/60,brace=.78*diag.A*1.829*4+3.2;const rawW=frame+deckW+brace; // VB CInt uses ties-to-even
 const roundEven=x=>Math.abs(x%1-.5)<1e-9?(Math.floor(x)%2===0?Math.floor(x):Math.ceil(x)):Math.round(x);
 const W0=p.weightMode==='auto'?roundEven(rawW):p.weight,WD=N*W0,WL=p.work*(p.dl+p.ll),WT=WD+WL,P=WT/2,lambda=p.k*p.step*100*p.unbraced/sec.r,{Cc,Fa}=compression(lambda,p.fy,p.E),allow=Fa*p.reduction,fa=P/sec.A,g=gust(p),w=wind(p,p.top,g),rows=[];
 const add=(name,demand,capacity,unit,note,group='main')=>rows.push({name,demand,capacity,unit,ratio:demand/capacity,note,group});
 add('立柱軸壓應力',fa,allow,'kgf/cm²','有效厚度 t − 腐蝕扣減；原 ASD 公式');add('壁連桿抗拉',w.F,p.tieT,'kgf','包含連接、錨定之整組容許拉力');add('壁連桿抗壓',w.F,p.tieC,'kgf','反向風；需計入桿件挫屈與接頭');
 let bracket=null;if(p.bracket){const custom=p.section==='custom',s=custom?{Ax:p.customA,Ix:p.customI,Sx:p.customS,Ash:p.customAw,Iv:p.customR**2*p.customA}:sections[Number(p.section)];const a=p.offset,b=a+p.width,B=p.B,D=p.D,L=Math.hypot(B,D),co=B/L,si=D/L,KGB=p.spacing/p.bay/p.pieces,Px=P*KGB,HB=Px*(a+b)/D,VB=(HB*L**3*si*co/3+HB*D*B*B/2-Px*(a**3+b**3)/6)/(L**3*co**2/3+B**3/3),VA=2*Px-VB,NC=HB*co+VB*si,MC=Math.abs(VB*B-HB*D),MA=Math.max(Math.abs(VA*a),Math.abs(VA*B-Px*(B-a)-Px*(B-b)),Math.abs(VA*b-Px*(b-a))),VC=Math.abs(HB*si-VB*co),VH=Math.max(Math.abs(VA),Math.abs(Px-VA),Math.abs(2*Px-VA)),r=custom?p.customR:Math.sqrt(s.Iv/s.Ax),sl=p.bracketK*L/r,comp=compression(sl,p.bracketFy,p.E),Fb=.6*p.bracketFy,Ft=Fb,Fv=.4*p.bracketFy,bend=M=>custom?M/s.Sx:M/Math.sqrt(2)*(1/s.Su+1/s.Sv),ra=HB/s.Ax/Ft+bend(MA)/Fb,rc=NC/s.Ax/comp.Fa+bend(MC)/Fb;
 add('托架 AC 拉彎互制',ra,1,'比值','原線性應力疊加法','bracket');add('托架 AC 剪應力',VH/s.Ash,Fv,'kgf/cm²','按剪力面積 Aw','bracket');add('托架 BC 壓彎互制',rc,1,'比值','原線性應力疊加法；非二階分析','bracket');add('托架 BC 剪應力',VC/s.Ash,Fv,'kgf/cm²','按剪力面積 Aw','bracket');
 const Ta=p.anchorT/p.anchorSF*p.anchorN,Va=p.anchorV/p.anchorSF*p.anchorN;add('A 點錨栓拉力',HB,Ta,'kgf','各端每一片托架之錨栓群','anchor');add('A 點錨栓剪力',Math.abs(VA),Va,'kgf','均勻分配假設','anchor');add('B 點錨栓剪力',Math.abs(VB),Va,'kgf','均勻分配假設','anchor');bracket={s,a,b,B,D,L,Px,KGB,HB,VA,VB,NC,MC,MA,VC,VH,r,sl,comp,Ta,Va,oldResultant:Math.hypot(HB,VA)/Math.hypot(Ta,Va),linearAnchor:HB/Ta+Math.abs(VA)/Va};}
 const profile=Array.from({length:21},(_,i)=>wind(p,p.base+(p.top-p.base)*i/20,g)),worst=rows.reduce((a,b)=>b.ratio>a.ratio?b:a),warnings=[];if(w.raw>1)warnings.push('原投影面積估算超出總面積，已上限為 1；請改用實測實體率。');if(lambda>200)warnings.push('立柱 KL/r > 200：超出本工具一般受壓構材檢核範圍，需重新配置側向支撐。');if(bracket&&bracket.sl>200)warnings.push('斜桿 KL/r > 200，須另行確認適用性。');if(p.gmode==='flexible'&&p.fn>=1)warnings.push('fn ≥ 1 Hz；目前仍採柔性公式，請確認振態設定。');if(p.step!==1.725&&p.weightMode==='auto')warnings.push('層高已調整；斜撐與踏板重量仍採原標準模組估算，宜改輸入實測組重。');if(!p.windConfirmed)warnings.push('風力係數、現地地況及施工架與建築物之互制尚未確認。');if(!p.capacityConfirmed)warnings.push('壁連桿及錨栓容量為示範值，尚未由產品試驗與基材條件確認。');if(!rows.every(x=>Number.isFinite(x.ratio))||!Number.isFinite(w.F)||!Number.isFinite(g.G))return {errors:['參數超出可計算範圍，請檢查尺寸、材料與動力參數']};return {errors:[],N,nom,sec,frame,deckW,brace,rawW,W0,WD,WL,WT,P,lambda,Cc,Fa,allow,fa,g,w,rows,bracket,profile,worst,warnings,empirical:(8.7-.1*(N-10))*1000/(4*2.5)};}
if(typeof module!=='undefined')module.exports={DEFAULTS,TERRAIN,tube,compression,gust,wind,calculate,validate};
