(function(){'use strict';
const R=ScaffoldRegulations,esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const saved=document.getElementById('scaffold-review-initial');let review=R.defaults();try{if(saved)review={...review,...JSON.parse(saved.textContent)};}catch{}
const titleState={pass:'數值符合',fail:'數值不符',pending:'待確認',info:'條件說明',recorded:'使用者已記錄'};
function help(){document.querySelectorAll('.field').forEach(f=>{const el=f.querySelector('input,select');if(!el||f.querySelector('.param-help')||!PARAMETER_HELP[el.id])return;const d=PARAMETER_HELP[el.id],box=document.createElement('details');box.className='param-help';box.innerHTML=`<summary aria-label="${esc(labels[el.id])}：定義與資料來源">ⓘ 定義與資料來源</summary><div id="definition-${el.id}"><p>${esc(d.definition)}</p><p><b>資料來源：</b>${esc(d.source)}</p></div>`;f.append(box);el.setAttribute('aria-describedby','definition-'+el.id);});}
function reviewBuild(){const host=$('regInputs');host.innerHTML=R.fields.map(([k,label,unit,,hint,opts])=>`<label>${esc(label)}${unit!=='select'&&unit!=='text'?'（'+unit+'）':''}${opts?`<select id="review-${k}">${opts.map(([a,b])=>`<option value="${a}"${review[k]===a?' selected':''}>${b}</option>`).join('')}</select>`:`<input id="review-${k}" type="${unit==='text'?'text':'number'}" ${unit==='text'?'maxlength="300"':'min="0" step="any"'} value="${esc(review[k])}">`}<small>${hint}</small></label>`).join('');$('regDocuments').innerHTML=R.documents.map(([k,t])=>`<label><input id="review-${k}" type="checkbox" ${review[k]?'checked':''}><span>${esc(t)}</span></label>`).join('');for(const k of Object.keys(review))$('review-'+k)?.addEventListener('input',e=>{review[k]=e.target.type==='checkbox'?e.target.checked:e.target.value;reviewRender();});}
function reviewRows(){return R.assess(current,review);}
function reviewRender(){if(last.errors.length){$('regSummary').textContent='先修正結構輸入，再顯示法規條件。';$('regResults').innerHTML='';$('reviewStrip').textContent='輸入需修正，法規條件暫不判定。';return;}
const rows=reviewRows(),fail=rows.filter(r=>r.state==='fail').length,pending=rows.filter(r=>r.state==='pending').length,docs=R.documents.filter(([k])=>!review[k]).length;
$('regSummary').textContent=`${fail} 項數值不符 · ${pending} 項條件待確認 · ${docs} 項文件／現場查驗未記錄`;
$('regResults').innerHTML=rows.map(r=>`<div class="reg-row"><strong>${esc(r.title)} <span class="reg-state ${r.state}">${titleState[r.state]}</span></strong><p>${esc(r.detail)}</p><small>${r.source}</small></div>`).join('');
$('reviewStrip').innerHTML=`框式施工架 · 規範核對 2026.10.09 · 法規 ${fail?fail+' 項數值不符':'尚須文件及現場確認'}<button type="button" id="openRegulations">查看法規檢核</button>`;$('openRegulations').onclick=()=>openTab('regulations');}
function openTab(id){document.querySelector(`nav button[data-tab="${id}"]`).click();window.scrollTo({top:0,behavior:'smooth'});}
const oldBuild=build;build=function(){oldBuild();help();};const oldRender=render;render=function(){oldRender();reviewRender();};
function layout(){const id=document.querySelector('nav button.active')?.dataset.tab;document.body.classList.toggle('extra-active',['regulations','tutorial'].includes(id));if(id!=='tutorial')$('tutorialVideo').pause();}
tabButtons.forEach(b=>b.addEventListener('click',layout));$('openTutorial').onclick=()=>openTab('tutorial');
const observer=new ResizeObserver(()=>document.documentElement.style.setProperty('--header-height',document.querySelector('header').offsetHeight+'px'));observer.observe(document.querySelector('header'));
function saveJSON(obj,name){const url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('saveCase').onclick=()=>{if(last.errors.length){$('caseStatus').textContent='請先修正輸入再保存。';return;}saveJSON({schema:'scaffold-case',version:1,parameters:current,review},'施工架案例.json');$('caseStatus').textContent='已匯出案例；請確認下載檔案。';};
$('caseImportPrompt')?.remove();let pendingCase=null;const importPrompt=document.createElement('div');importPrompt.id='caseImportPrompt';importPrompt.className='notice';importPrompt.hidden=true;importPrompt.innerHTML='<p>匯入將取代目前參數與法規紀錄。需要保留時，先按「儲存案例 JSON」。</p><button type="button" id="confirmCaseImport">確認匯入</button> <button type="button" id="cancelCaseImport">取消</button>';$('reviewStrip').before(importPrompt);
function parseCase(data){if(data.schema!=='scaffold-case'||data.version!==1||!data.parameters||typeof data.parameters!=='object')throw Error('不是支援的施工架案例檔。');const p={...DEFAULTS};for(const [k,v]of Object.entries(data.parameters)){if(!Object.hasOwn(DEFAULTS,k))throw Error('未知參數：'+k);if(k==='section'){if(v!=='custom'&&(!Number.isInteger(Number(v))||Number(v)<0||Number(v)>22))throw Error('斷面選項無效');}else if(typeof v!==typeof DEFAULTS[k]||(typeof v==='number'&&!Number.isFinite(v)))throw Error('參數格式不符：'+k);p[k]=v;}const err=calculate(p,SECTIONS).errors;if(err.length)throw Error(err.join('；'));const rv=R.defaults();if(data.review){for(const [k,v]of Object.entries(data.review)){if(!Object.hasOwn(rv,k))throw Error('未知法規欄位');const f=R.fields.find(f=>f[0]===k);if(!f){if(typeof v!=='boolean')throw Error('查驗欄位應為勾選值');}else if(f[2]==='select'){if(!f[5].some(o=>o[0]===v))throw Error('法規選項無效');}else if(f[2]==='text'){if(typeof v!=='string'||v.length>300)throw Error('文件編號格式無效');}else if(v!==''&&(!Number.isFinite(Number(v))||Number(v)<0||!['number','string'].includes(typeof v)))throw Error('法規數值應為非負數');rv[k]=v;}}return {p,rv};}
$('loadCase').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>100000)throw Error('案例檔超過 100 KB，請確認檔案。');pendingCase=parseCase(JSON.parse(await f.text()));importPrompt.hidden=false;$('confirmCaseImport').focus();$('caseStatus').textContent='案例已讀取，請確認是否載入。';}catch(err){$('caseStatus').textContent='未匯入：'+err.message;}finally{e.target.value='';}};
$('cancelCaseImport').onclick=()=>{pendingCase=null;importPrompt.hidden=true;};$('confirmCaseImport').onclick=()=>{if(!pendingCase)return;current=pendingCase.p;review=pendingCase.rv;pendingCase=null;importPrompt.hidden=true;reviewBuild();build();$('caseStatus').textContent='已載入案例及法規查驗紀錄。';};
// Scope of legal checks is exported in the same report snapshot as calculations.
$('exampleLoadConfirm').addEventListener('click',()=>{review=R.defaults();reviewBuild();reviewRender();});const originalReset=$('reset').onclick;$('reset').onclick=()=>{const before=current;originalReset();if(current!==before){review=R.defaults();reviewBuild();reviewRender();}};
const snapshot=ScaffoldExecution.snapshot;ScaffoldExecution.snapshot=function(){const data=snapshot();data.tables.push({title:'施工架法規条件與查驗紀錄（2026-10-09）',source:'營造安全衛生設施標準115.06.30版（第11-2條尚未生效）；https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=N0060014 。數值篩檢不代表整架或CNS認證。',headers:['項目／條文','狀態','依據與本次設定'],rows:reviewRows().map(r=>[r.title+' '+r.source,titleState[r.state],r.detail]).concat(R.fields.map(f=>[f[1],String(review[f[0]]===''?'未填':review[f[0]]),f[2]])).concat(R.documents.map(([k,t])=>[t,review[k]?'使用者已記錄':'未記錄','須附佐證'])),widths:[2600,1500,5260]});return data;};
// Preserve legal input state in the existing self-contained offline export.
$('offline').addEventListener('click',()=>{},false);
const priorOffline=$('offline').onclick;$('offline').onclick=()=>{let el=$('scaffold-review-initial');if(!el){el=document.createElement('script');el.type='application/json';el.id='scaffold-review-initial';document.head.append(el);}el.textContent=JSON.stringify(review).replace(/</g,'\\u003c');priorOffline();};
$('tutorialVideo').addEventListener('error',()=>{$('videoStatus').textContent='影片載入失敗；請連線後重試，或下載完整離線套件。';});
window.ScaffoldUpgrade={reviewRows,getReview:()=>({...review}),parseCase};help();reviewBuild();reviewRender();layout();if(['#regulations','#tutorial'].includes(location.hash))openTab(location.hash.slice(1));
})();
