/* Editable native DOCX report, fully local. No HTML disguised as .doc. */
(function(global){
'use strict';
const n=(x,d=4)=>Number.isFinite(x)?x.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
function makeReport(data,lib){
 const {Document,Paragraph,TextRun,Table,TableRow,TableCell,WidthType,BorderStyle,AlignmentType,VerticalAlign,Footer,PageNumber}=lib;
 const {p,r,inputs,blocks}=data;if(r.errors?.length)throw Error('請先修正輸入參數，再匯出計算書。');
 const children=[];const text=(s,style='Normal')=>new Paragraph({style,children:[new TextRun({text:String(s),font:{name:'Noto Sans CJK TC',eastAsia:'Noto Sans CJK TC'}})]});
 const para=s=>children.push(text(s));const head=s=>children.push(text(s,'Heading1'));
 const border={style:BorderStyle.SINGLE,size:4,color:'D9D9D9'};
 function table(headers,rows,widths){children.push(new Table({width:{size:9360,type:WidthType.DXA},columnWidths:widths,borders:{top:border,bottom:border,left:border,right:border,insideHorizontal:border,insideVertical:border},rows:[headers,...rows].map((row,i)=>new TableRow({tableHeader:i===0,cantSplit:true,children:row.map((v,j)=>new TableCell({width:{size:widths[j],type:WidthType.DXA},verticalAlign:VerticalAlign.CENTER,shading:{fill:i===0?'DAE6F2':'FFFFFF'},margins:{top:90,bottom:90,left:110,right:110},children:[new Paragraph({alignment:j===0?AlignmentType.LEFT:AlignmentType.CENTER,spacing:{after:0,line:270},children:[new TextRun({text:String(v),bold:i===0,size:20,font:{name:'Noto Sans CJK TC',eastAsia:'Noto Sans CJK TC'},color:'000000'})]})]}))}))}));children.push(new Paragraph({spacing:{after:60},children:[]}));}
 children.push(text('施工鷹架詳細計算書','Title'));
 para(`計算日期 ${data.date}　　${data.example?'預設範例參數':'目前畫面參數'}　　單位 kgf cm m`);
 const fails=r.rows.filter(x=>x.ratio>1).length;
 para(`本計算書包含立柱軸壓、風力與壁連桿${p.bracket?'、三角托架及錨栓個別拉剪':''}檢核。已計算項目共有 ${r.rows.length} 項，其中 ${fails} 項超限；控制項目為${r.worst.name}，使用比 ${n(r.worst.ratio,3)}。本結果不包含整體穩定及完整連接破壞模式。`);
 para(`風場適用性確認：${p.windConfirmed?'已勾選確認':'尚未確認'}。容量依據確認：${p.capacityConfirmed?'已勾選確認':'尚未確認'}。預設輸入值不得直接視為本案實測資料。`);
 head('檢核結果總表');table(['檢核項目','需求','容量','單位','比值','結果'],r.rows.map(x=>[x.name,n(x.demand,3),n(x.capacity,3),x.unit,n(x.ratio,3),x.ratio>1?'NG':'OK']),[2400,1450,1450,1350,1450,1260]);
 head('設計輸入資料');para('以下為匯出當下的完整參數快照。未啟用模式的欄位仍保留設定值，計算時僅採用所選模式。');table(['輸入項目','設定值','單位'],inputs,[4400,3260,1700]);
 for(const block of blocks){head(block.title.replace(/^\d+\s*/,'').replace(/[　]/g,' ').trim());for(const part of block.parts){if(part.kind==='formula'){for(const line of part.text.split('\n').map(x=>x.trim()).filter(Boolean))children.push(text(line,'Formula'));}else para(part.text);}}
 head('數值代入補充');
 const D=p.d/10,t=(p.t-p.loss)/10,x=r.lambda/r.Cc;
 para('立柱斷面及容許壓應力');
 for(const s of [`D = ${n(p.d,2)} / 10 = ${n(D)} cm；t有效 = (${n(p.t,2)} − ${n(p.loss,2)}) / 10 = ${n(t)} cm`,`A = π/4 × [${n(D)}² − (${n(D)} − 2×${n(t)})²] = ${n(r.sec.A)} cm²`,`I = π/64 × [${n(D)}⁴ − (${n(D)} − 2×${n(t)})⁴] = ${n(r.sec.I)} cm⁴`,`λ = ${n(p.k)} × (${n(p.step)} × 100 × ${n(p.unbraced)}) / ${n(r.sec.r)} = ${n(r.lambda)}`,`Cc = √(2 × π² × ${n(p.E,0)} / ${n(p.fy,0)}) = ${n(r.Cc)}；x = ${n(x)}`,r.lambda<r.Cc?`Fa = [1 − ${n(x)}²/2] × ${n(p.fy,0)} / [5/3 + 3×${n(x)}/8 − ${n(x)}³/8] = ${n(r.Fa)} kgf/cm²`:`Fa = 12 × π² × ${n(p.E,0)} / [23 × ${n(r.lambda)}²] = ${n(r.Fa)} kgf/cm²`,`ηFa = ${n(p.reduction)} × ${n(r.Fa)} = ${n(r.allow)} kgf/cm²`,`fa/(ηFa) = (${n(r.P)} / ${n(r.sec.A)}) / ${n(r.allow)} = ${n(r.fa/r.allow)}　${r.fa/r.allow>1?'NG':'OK'}`])children.push(text(s,'Formula'));
 const tr={A:[.32,500],B:[.25,400],C:[.15,300]}[p.terrain];para('風速壓及壁連桿需求');
 for(const s of [`K(z) = 2.774 × [max(${p.top},5)/${tr[1]}]^(2×${tr[0]}) = ${n(r.w.Kz)}`,`q = 0.06 × ${n(r.w.Kz)} × ${n(p.kzt)} × (${n(p.importance)} × ${n(p.v)})² = ${n(r.w.q)} kgf/m²`,p.windMode==='net'?`p風 = ${n(r.w.q)} × ${n(r.w.cf)} = ${n(r.w.pressure)} kgf/m²`:`p風 = ${n(r.w.q)} × ${n(r.g.G)} × ${n(r.w.cf)} × ${n(r.w.areaFactor)} = ${n(r.w.pressure)} kgf/m²`,`F = ${n(r.w.pressure)} × ${n(p.tieX)} × ${n(p.tieY)} = ${n(r.w.F)} kgf`,`抗拉比 = ${n(r.w.F)} / ${n(p.tieT)} = ${n(r.w.F/p.tieT)}；抗壓比 = ${n(r.w.F)} / ${n(p.tieC)} = ${n(r.w.F/p.tieC)}`])children.push(text(s,'Formula'));
 if(p.gmode==='flexible'){para('柔性陣風反應完整公式');for(const s of ['Vz̄ = b(z̄/10)^α V10(C)；N1 = fn Lz̄ / Vz̄','Rn = 7.47 N1 / (1 + 10.3 N1)^(5/3)','ηh = 4.6 fn h / Vz̄；ηB = 4.6 fn B / Vz̄；ηL = 15.4 fn L / Vz̄','Rj = 1/ηj − [1 − exp(−2ηj)]/(2ηj²)；ηj = 0 時 Rj = 1','R = √[Rn Rh RB (0.53 + 0.47 RL) / β]','gR = √[2 ln(3600 fn)] + 0.577 / √[2 ln(3600 fn)]',`β = ${n(p.beta)}；Gf = ${n(r.g.G)}；其餘中間值詳陣風反應章節。`])children.push(text(s,'Formula'));}
 if(r.bracket){const b=r.bracket;para('三角托架數值代入');for(const s of [`P = (${n(r.WT)}/2) × (${p.spacing}/${p.bay}/${p.pieces}) = ${n(b.Px)} kgf`,`HB = ${n(b.Px)} × (${b.a}+${b.b}) / ${b.D} = ${n(b.HB)} kgf`,`c = ${b.B}/${n(b.L)} = ${n(b.B/b.L)}；s = ${b.D}/${n(b.L)} = ${n(b.D/b.L)}`,`VB 分子 = HB L³sc/3 + HB DB²/2 − P(a³+b³)/6 = ${n(b.HB*b.L**3*(b.D/b.L)*(b.B/b.L)/3+b.HB*b.D*b.B*b.B/2-b.Px*(b.a**3+b.b**3)/6)} kgf·cm³`,`VB 分母 = L³c²/3 + B³/3 = ${n(b.L**3*(b.B/b.L)**2/3+b.B**3/3)} cm³`,`VB = ${n(b.VB)} kgf；VA = 2×${n(b.Px)} − ${n(b.VB)} = ${n(b.VA)} kgf`,`斜桿 λ = ${p.bracketK} × ${n(b.L)} / ${n(b.r)} = ${n(b.sl)}`,`A端錨栓拉力比 = ${n(b.HB)} / (${p.anchorN}×${p.anchorT}/${p.anchorSF}) = ${n(b.HB/b.Ta)}`,`A端錨栓剪力比 = ${n(Math.abs(b.VA))} / (${p.anchorN}×${p.anchorV}/${p.anchorSF}) = ${n(Math.abs(b.VA)/b.Va)}`,`B端錨栓剪力比 = ${n(Math.abs(b.VB))} / (${p.anchorN}×${p.anchorV}/${p.anchorSF}) = ${n(Math.abs(b.VB)/b.Va)}`])children.push(text(s,'Formula'));}
 head('不同高度的壁連桿風力');para(`各高度均採相同分攤面積 ${n(r.w.area)} m²，設計檢核使用頂端風力包絡。`);table(['高程 m','Kz','q kgf/m²','風力 kgf'],r.profile.map(w=>[n(w.z,2),n(w.Kz),n(w.q,2),n(w.F,2)]),[1900,2260,2600,2600]);
 head('計算假設與適用限制');for(const s of [...r.warnings,'立框垂直載重由兩支立柱均分；托架各片等分受力，兩構件 EI 相同並忽略軸向變形。','角鋼應力採原程式線性疊加；自訂斷面須使用適當剪力面積與最小迴轉半徑。','風力表 2.10 與表 2.11 套用施工架屬工程類比。附著式鷹架須確認建築物干擾、渦流、角隅、局部風壓及反向風；遮網實體率不等於風壓折減係數。','錨栓僅列個別拉剪需求及原式參考。拉剪互制、基材錐狀破壞、劈裂、拉拔、群效應、邊距、撬力與承壓須另行檢核。','未計算地震、整架傾覆滑移、基底承載、風致立柱彎矩與二階效應、扣件、焊縫及板面撓度。各列 OK 不代表整體施工架可直接施工。','計算採完整精度，文件顯示值四捨五入，直接用顯示數字重算可能有末位差異。'])para(s);
 head('計算依據');for(const s of ['原始碼 鷹架設計 更新程式碼 NEW 20140731 20140731 FoundationDesign FormMain.vb，更新日期 2016-08-15。重量、立柱與托架計算採原架構；自訂斷面細長比、腐蝕折減與風力更新詳網頁修正紀錄。','風力採內政部 建築物耐風設計規範及解說 104 年施行版，含 103-12-03 第 2.4 點及表 2.21 修正；版本查核日期 2026-10-01。主要依據為第二章第 2.2、2.4 至 2.8 節，表 2.2、2.10、2.11。','國土署規範公告 https://www.nlma.gov.tw/ch/legislation/regsearch/166','第二章 https://www.nlma.gov.tw/uploads/files/ed1498837647323cbd8cd287ce939972.pdf','規範圖表 https://www.nlma.gov.tw/uploads/files/31dfde31df0c1be76c1b8d92e4285d76.pdf'])para(s);
 return new Document({creator:'施工鷹架分析設計',title:'施工鷹架詳細計算書',description:'依匯出時參數產生的可編輯計算書',styles:{default:{document:{run:{font:{name:'Noto Sans CJK TC',eastAsia:'Noto Sans CJK TC'},size:22,color:'000000'},paragraph:{spacing:{after:110,line:310}}}},paragraphStyles:[{id:'Title',name:'Title',basedOn:'Normal',next:'Normal',run:{size:36,bold:true,color:'000000'},paragraph:{spacing:{before:0,after:220},keepNext:true}},{id:'Heading1',name:'Heading 1',basedOn:'Normal',next:'Normal',run:{size:27,bold:true,color:'000000'},paragraph:{spacing:{before:260,after:130},keepNext:true,outlineLevel:0}},{id:'Formula',name:'Formula',basedOn:'Normal',run:{size:21},paragraph:{spacing:{after:100,line:295},keepLines:true}}]},sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:1080,bottom:1080,left:1440,right:1440}}},footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({children:['第 ',PageNumber.CURRENT,' 頁'],size:18})]})]})},children}]});
}
global.ScaffoldWord={makeReport};
})(typeof window!=='undefined'?window:globalThis);
